---
abstract: 'Generate SQL from Perl data structures'
author:
  - 'Nathan Wiger <nate@wiger.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Storable: 0
  Test::Deep: 0.106
  Test::Exception: 0
  Test::More: 0.92
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract
no_index:
  directory:
    - examples
    - inc
    - t
  package:
    - DBIx::Class::Storage::Debug::PrettyPrint
requires:
  Class::Accessor::Grouped: 0.10002
  Getopt::Long::Descriptive: 0.086
  Hash::Merge: 0.12
  List::Util: 0
  Scalar::Util: 0
  perl: 5.6.2
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SQL-Abstract
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/SQL-Abstract.git
version: 1.72
