---
abstract: 'Generate SQL from Perl data structures'
author:
  - 'Nathan Wiger <nate@wiger.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Storable: 0
  Test::Deep: 0.106
  Test::Exception: 0
  Test::More: 0.92
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract
no_index:
  directory:
    - examples
    - inc
    - t
  package:
    - DBIx::Class::Storage::Debug::PrettyPrint
requires:
  Class::Accessor::Grouped: 0.09005
  Hash::Merge: 0.12
  List::Util: 0
  Scalar::Util: 0
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
version: 1.67_03
